name:                hethet-api
version:             0.0.1
github:              "NousadS/hethet-api"
license:             MIT
author:              "Nousad"
maintainer:          "nousad.cat@gmail.com"
copyright:           "2024 Nousad"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            PetPet API on Haskell.
category:            Web

description:         See README.md

dependencies:
- base >= 4.7 && < 5
- wai >= 3.2.4
- http-types >= 0.12.4
- warp >= 3.3.31
- bytestring >= 0.11.5.3
- case-insensitive >= 1.2.1.0
- text
- split
- JuicyPixels >= 3.3.0
- vector >= 0.12.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hethet-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hethet-api
Ñ‘